# Generated by Django 3.2.9 on 2021-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOnWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('object', models.TextField()),
                ('message', models.TextField()),
                ('user_name', models.CharField(max_length=255)),
                ('group_id', models.IntegerField()),
                ('message_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись на стене',
                'verbose_name_plural': 'Записи на стене',
            },
        ),
    ]
